// <auto-generated />
using System;
using EpinelPS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpinelPS.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260705005727_GameUserExpansion1")]
    partial class GameUserExpansion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("EpinelPS.Models.GameUser", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BanEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BanStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("DispatchCollectionLv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispatchFavoriteLv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispatchLv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispatchResetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GachaTutorialPlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfraCoreExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfraCoreLvl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAction")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastClearedDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastHardStageCleared")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastNormalStageCleared")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReset")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastStoryStageCleared")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWeeklyReset")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProfileIconIsPrism")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SynchroDeviceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SynchroDeviceUpgraded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("sickpulls")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EpinelPS.Models.SdkUser", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisterTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("SdkUsers");
                });

            modelBuilder.Entity("EpinelPS.Models.TriggerModelNew", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConditionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("EpinelPS.Models.TriggerModelNew", b =>
                {
                    b.HasOne("EpinelPS.Models.GameUser", "User")
                        .WithMany("Triggers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EpinelPS.Models.GameUser", b =>
                {
                    b.Navigation("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
