// <auto-generated />
using EpinelPS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpinelPS.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260703214723_InitialCreate_07-03-2026")]
    partial class InitialCreate_07032026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
#pragma warning restore 612, 618
        }
    }
}
