using ASodium;
using EpinelPS.Database;
using EpinelPS.Utils;
using Google.Protobuf;
using Paseto;
using Paseto.Builder;
using System.Text.Json;

namespace EpinelPS.LobbyServer;

public static class LobbyHandler
{

    /// <summary>
    /// Private key, Token
    /// </summary>
    /// <param name="publicKey"></param>
    /// <returns></returns>
    public static GameClientInfo GenGameClientTok(ByteString publicKey, ulong userId)
    {
        string token = Rng.RandomString(381);

        GameClientInfo info = new() { ClientPublicKey = [.. publicKey] };

        SodiumKeyExchangeSharedSecretBox box = SodiumKeyExchange.CalculateServerSharedSecret(JsonDb.ServerPublicKey, JsonDb.ServerPrivateKey, [.. publicKey]);

        info.Keys = box;
        info.ClientAuthToken = token;

        if (userId == 0)
            throw new Exception("expected user account");

        info.UserId = userId;

        return info;
    }

    public static GameClientInfo? GetInfo(string token)
    {
        PasetoTokenValidationResult encryptionToken = new PasetoBuilder().Use(ProtocolVersion.V4, Purpose.Local)
                         .WithKey(JsonDb.Instance.LauncherTokenKey, Encryption.SymmetricKey)
                         .Decode(token, new PasetoTokenValidationParameters() { ValidateLifetime = true }) ?? throw new Exception("failed to decrypt");
        JsonElement elem = (encryptionToken.Paseto.Payload["data"] as System.Text.Json.JsonElement?) ?? throw new Exception("expected data field in auth token");

        string p = elem.GetString() ?? throw new Exception("auth token cannot be null");

        return JsonSerializer.Deserialize<GameClientInfo>(p ?? throw new Exception("data cannot be null"));
    }

    public static void Init()
    {
        // By calling this function, we force .NET to initialize handler dictanary to catch errors early on.
    }

    public static NetUserData CreateNetUserDataFromUser(User user)
    {
        NetUserData ret = new()
        {
            Lv = user.userPointData.UserLevel,
            Exp = user.userPointData.ExperiencePoint,
            CostumeLv = 1,
            Frame = user.ProfileFrame,
            Icon = user.ProfileIconId,
            IconPrism = user.ProfileIconIsPrism,
            InfraCoreExp = user.InfraCoreExp,
            InfraCoreLv = user.InfraCoreLvl,
            Desc = user.Description
        };


        // Restore completed tutorials.
        foreach (KeyValuePair<int, ClearedTutorialData> item in user.ClearedTutorialDataNew)
        {
            ret.Tutorials.Add(new NetTutorialData()
            {
                GroupId = item.Key,
                LastClearedTid = item.Value.Id,
                LastClearedVersion = item.Value.VersionGroup
            });
        }

        ret.CounselCount = user.ResetableData.DailyCounselCount[1];
        ret.OutpostFastBattleCount = user.ResetableData.WipeoutCount;        
        return ret;
    }
    public static NetWholeUserData CreateWholeUserDataFromDbUser(User user)
    {
        using var ctx1 = GameContext.CreateNew();
        var userDB = ctx1.Users.Find((ulong)user.ID);
        NetWholeUserData ret = new()
        {
            Lv = user.userPointData.UserLevel,
            Frame = user.ProfileFrame,
            Icon = user.ProfileIconId,
            IconPrism = user.ProfileIconIsPrism,
            UserTitleId = user.TitleId,
            Nickname = userDB.Nickname,
            Usn = (long)user.ID,
            LastActionAt = DateTimeOffset.UtcNow.Ticks,
            Server = 1001
        };

        return ret;
    }

    public static NetWholeUserData CreateWholeUserDataFromDbUser(ulong id)
    {
        using var ctx2 = GameContext.CreateNew();
        var userDB = ctx2.Users.Find((ulong)id);
        /*var user = JsonDb.Instance.Users.Where(x=>x.ID == id).FirstOrDefault();
        NetWholeUserData ret = new()
        {
            Lv = user.userPointData.UserLevel,
            Frame = user.ProfileFrame,
            Icon = user.ProfileIconId,
            IconPrism = user.ProfileIconIsPrism,
            UserTitleId = user.TitleId,
            Nickname = userDB.Nickname,
            Usn = (long)user.ID,
            LastActionAt = DateTimeOffset.UtcNow.Ticks,
            Server = 1001
        };*/

        return new NetWholeUserData();
    }
}

public class GameClientInfo
{
    /// <summary>
    /// Client public key generated by game client
    /// </summary>
    public byte[] ClientPublicKey { get; set; } = [];
    /// <summary>
    /// Authentication token
    /// </summary>
    public string ClientAuthToken { get; set; } = "";
    /// <summary>
    /// Rx/Tx key pair
    /// </summary>
    public SodiumKeyExchangeSharedSecretBox Keys { get; set; } = new();
    /// <summary>
    /// User ID of the user
    /// </summary>
    public ulong UserId { get; set; }
}
