namespace EpinelPS.LobbyServer.Event
{
    public enum EventType : int
    {
        None = 0,
        DailyMissionEvent = 1,
        LoginEvent = 2,
        ViewShortCut = 3,
        CooperationEvent = 4,
        StoryEvent = 5,
        PickupGachaEvent = 6,
        PollEvent = 7,
        ComeBackUserEvent = 8,
        EventPass = 9,
        FieldHubEvent = 10,
        ShopEvent = 11,
        MissionEvent = 12,
        ChargeGachaEvent = 13,
        MiniGameSortOut = 14,
        CharacterSkillResetEvent = 15,
        EventQuest = 16,
        RewardUpEvent = 17,
        SDBattleEvent = 18,
        TextAdventure = 19,
        ChallengeModeEvent = 20,
        DailyFreeGachaEvent = 21,
        BoxGachaEvent = 22,
        DiceEvent = 23,
        BBQTycoon = 24,
        CE002MiniGame = 25,
        TriggerMissionEventReward = 26,
        ArenaRookieGroupShuffle = 27,
        ArenaSpecialGroupShuffle = 28,
        NKSMiniGame = 29,
        DatingSimulator = 30,
        DessertRush = 31,
        CE003MiniGame = 32,
        TowerDefense = 33,
        EventPlaySoda = 34,
        IslandAdventure = 35,
        MiniGameDD = 36,
        CE004MiniGame = 37,
        MVGMiniGame = 38,
        DragonDungeonRunMiniGame = 39,
        NewPlayerLottery = 40,
        PirateCafe = 41,
        CEEvaMiniGame = 42,
        BubbleMarchMiniGame = 43,
        CE006BossChallengeMiniGame = 44,
        SupportCharacterEvent = 45,
        GachaBoard = 46,
        FreeRewardPass = 47,
        GachaPayback = 48,
        FieldCollectEvent = 49,
        MiniGameBTG = 50
    }
}
